// MediaPipe Pose 33개 관절점 인덱스
export const POSE_CONSTANTS = {
  // 얼굴
  NOSE: 0,
  LEFT_EYE: 1,
  RIGHT_EYE: 2,
  LEFT_EAR: 3,
  RIGHT_EAR: 4,
  
  // 상체
  LEFT_SHOULDER: 11,
  RIGHT_SHOULDER: 12,
  LEFT_ELBOW: 13,
  RIGHT_ELBOW: 14,
  LEFT_WRIST: 15,
  RIGHT_WRIST: 16,
  
  // 하체
  LEFT_HIP: 23,
  RIGHT_HIP: 24,
  LEFT_KNEE: 25,
  RIGHT_KNEE: 26,
  LEFT_ANKLE: 27,
  RIGHT_ANKLE: 28,
  
  // 발
  LEFT_FOOT_INDEX: 31,
  RIGHT_FOOT_INDEX: 32,
  
  // 손
  LEFT_THUMB: 19,
  RIGHT_THUMB: 20,
  LEFT_INDEX: 21,
  RIGHT_INDEX: 22,
  LEFT_PINKY: 17,
  RIGHT_PINKY: 18
} as const; 